spring:
  application:
    name: FINASIT
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000 # 30 segundos
      connection-timeout: 20000 # 20 segundos
      max-lifetime: 1800000 # 30 minutos
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    user:
      name: user
      password: 1234
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect