spring:
  application:
    name: FINASIT
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
jwt:
  secret:
    key: ${JWT_SECRET_KEY}


#logging:
#  level:
#    org:
#      springframework : DEBUG