spring:
  application:
    name: FINASIT
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

server:
  port: 80
