spring:
  application:
    name: FINASIT
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
jwt:
  expiration: 43200000
  secret:
    key: ${JWT_SECRET_KEY}
  cookie:
    name: ${JWT_COOKIE_NAME}
    expiration: ${JWT_EXPIRATION}
  refresh-token:
    expiration: 604800000

domain: ${DOMAIN}

server:
  port: 80
