spring:
  application:
    name: FINASIT
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false



#logging:
#  level:
#    org:
#      springframework : DEBUG